### ISSUE TITLE
Invalid APK

### ISSUE THREAD

**Issue by frlemoine** [vaibhavpandeyvpz/apkstudio#103]
Hi all,
I've tried to decompile/compile APK without any changes but Andoid install refuse to install the new APK.
It always says that there is a problem whan verifying the package. 
And the new compiled.apk is always 35 Ko less than the original APK.

I've tried on various APK.
My PC is running XP (I know, it's old fashion).

Thanks !

**Comment by Surendrajat** [comment]
Are you using latest version of APK Studio?
If yes, could you please upload console log somewhere like pastebin and provide the link here?
I suspect its something to do with apk signer but not sure until I check the logs.

**Comment by frlemoine** [comment]
Hi,
First, thank for your answer.
The version I use is APK Studio d49d3de.
Decompile console log 

$ java -Xmx128m -jar "C:/Documents and Settings/frlemoine/.apkstudio/vendor/apktool.jar" -f d C:/scripts/RssDemon.apk -o C:/scripts/RssDemon
I: Using Apktool 2.0.2 on RssDemon.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Documents and Settings\frlemoine\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Process exited with code 0

Then compile log without any changes : 

$ java -Xmx128m -jar "C:/Documents and Settings/frlemoine/.apkstudio/vendor/apktool.jar" -f b C:/scripts/RssDemon -o C:/scripts/RssDemon.apk
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Building apk file...
Process exited with code 0

I don't use signing or export.

Regards !

**Comment by Surendrajat** [comment]
Hi again @frlemoine !
So this is indeed related to apk signing. Well, it's necessary to sign an APK after rebuilding it unless you've disabled verification in device which clearly isn't the case here.
The error and the reduced size of apk are due to not signing the APK.
I'd recommend you to download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [these instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements). This version let you not worry about providing keystore etc. Simply click on sign icon and your app will be signed with an embedded keystore.
Hope this solves your issue.

**Comment by pemgithub** [comment]
how do you disable verification
