### ISSUE TITLE
AppImage lacks required components

### ISSUE THREAD

**Issue by probonopd** [vaibhavpandeyvpz/apkstudio#106]
When running the AppImage, getting

> You need to download some 3rd-party applications/files and place them in proper directory for APK Studio to work. 

![](https://github.com/AppImage/appimage.github.io/raw/a18e167f1c6e091457b6ce1fcd800bf83f9f77b5/database/APK_Studio/screenshot.png)

All the things mentioned in https://github.com/vaibhavpandeyvpz/apkstudio#requirements should be bundled inside the AppImage, so that the user does not need to download additional things, just the AppImage.

See https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages for more information.

Reference:
https://github.com/AppImage/appimage.github.io/pull/458

**Comment by Surendrajat** [comment]
I know APK Studio isn't quite fit for AppImage concept in this way (and I, too, wanted to eliminate this headache for users) but, is it really necessary to do so?
Because I've got few reasons for excluding those components from the package. For example:
- **Updates**: `apktool` is about to get new update in a week or so and `uber-apk-signer` wasn't stable until recently. I think it's better if APK Studio isn't affected with the changes in those components, like in its past, and doesn't require to be updated unnecessarily.
- **Size and Re-usability**: Those binaries sum up to ~7mb which isn't much but since, in most cases, a person working with APK Studio has `apktool` and `uber-apk-signer` already installed and those can be detected automatically, I don't think its good idea to increase AppImage size further as it's already bundling Qt libs.

I've seen and closed so many issues here all of which were because of the installer with outdated `apktool`. 
So, do you think it's okay if APK Studio is dependent on those external components for the time being?

**Comment by probonopd** [comment]
> So, do you think it's okay if APK Studio is dependent on those external components for the time being?

As the application author, it's your choice. But the AppImage philosophy is that an AppImage should not have any dependencies apart from what comes with the base system. This is one of the reasons for the simplicity for users.

Of course you can continue to do what you are doing now, but the downsides are:

* Users need more time and hassle to make everything work
* Your application will not be listed on the AppImageHub central directory of available AppImages because it violates the "one app = one file" philosophy of AppImage
* Users need to update the external dependencies manually, rather than just being able to update the whole AppImage and being done with it

**Comment by Surendrajat** [comment]
I got you point :)
I'll try implement this update mechanism but it will take a while until I figure something out similar for Windows as well(it's not very cool to have two version of guide, is it?).
Do you have some suggestions about how to achieve it for Windows?

**Comment by probonopd** [comment]
> Do you have some suggestions about how to achieve it for Windows?

Unfortunately no, as I don't use Windows...

**Comment by Surendrajat** [comment]
Ah, Neither do I :)
I'll be happy if someone could help here to implement it.

**Comment by vaibhavpandeyvpz** [comment]
@Surendrajat I am back :D to help you on this

**Comment by Surendrajat** [comment]
@vaibhavpandeyvpz cool :) I'm afraid you'll have to start it for now but I'll try to join asap. Welcome back!
P.S.  I've created a project in order to track future development better.

**Comment by vaibhavpandeyvpz** [comment]
It requires `java`, `apktool`, `jadx`, `uber-apk-signer`, `adb`. On linux, not all distros have `adb` in their package repository so need to package `platform-tools (12 mb)`, `apktool (16 mb)`, `uber-apk-signer (2mb)` and `jadx (10 mb)` which totals into a whopping `40 mb` extra in download size. Point it, the user might have any if not all of those already on their systems installed differently. They can just provide a path to their existing files in **Settings > BInaries** now.

**Comment by probonopd** [comment]
> It requires java, apktool, jadx, uber-apk-signer, adb.

Then all of these and their dependencies should be bundled in the AppImage.
