### ISSUE TITLE
Improving vendor.zip UX: system-wide default

### ISSUE THREAD

**Issue by wlritchi** [vaibhavpandeyvpz/apkstudio#12]
Hi,

I'm the current maintainer of the [apkstudio-git package](https://aur.archlinux.org/packages/apkstudio-git/) on the [Arch Linux User Repository](https://aur.archlinux.org/). The latest version of apkstudio requires placing vendor.zip in the user's home directory by default, which means that on first run, users are told to take additional steps to get the software working. Would it be possible to have apkstudio check for a system vendor.zip in some location so that the apkstudio-git package could simply install it to that location?

Thanks,
William Luc Ritchie

**Comment by vaibhavpandeyvpz** [comment]
@wlritchi well I chose **~/.apkstudio** because it would be writeable to every-user and allow him/her to update and choose **apktool** version as per their needs. If you prefer to install it to a system-wide location along the original apkstudio install itself, then you can suggest a comfortable location where arch's package manager can install it to and I will add it to the search location(s) for vendor so that users may need not to download another few bytes to get started.

**Comment by wlritchi** [comment]
I'd suggest /usr/lib/apkstudio/vendor.zip if it's architecture-dependent, or /usr/share/apkstudio/vendor.zip if not (cursory glance suggests the latter). If vendor.zip is likely going to be a long-term solution rather than a short-term fix, it would probably be best to make it a build flag.

**Comment by vaibhavpandeyvpz** [comment]
actually the vendor.zip contains some os/arch independent java executables/libraries (as of now) which need to be **extracted** to a folder so that apkstudio can run or reference them. I would prefer somewhere in **/opt/apkstudio**. What you prefer?

**Comment by wlritchi** [comment]
Thinking more about it and consulting with others, build flag is probably not necessary; /usr/share is standard enough. As for where apkstudio extracts the zip, that's outside the scope of packaging, but would it make sense to do it somewhere under the user's homedir? Where does it do it currently?

**Comment by vaibhavpandeyvpz** [comment]
apkstudio doesn't extract the archive. it needs to be downloaded and extracted by the user. if the user extracts it to ~/.apkstudio/vendor then it picks it up auto otherwise one can set the custom extracted path in Edit > Settings. Not integrating the auto download/extract within-by apkstudio wasn't implemented because of 2 reasons:
- I wanted users to be aware of whats is vendor.zip, so that they can update **apktool** after initial install (if required).
- Unpacking ZIPs are not directly supported by Qt in a cross-platform way without use of additional library.

**Comment by wlritchi** [comment]
Oh, I misread the instructions, sorry. Long day. If apkstudio expects them already extracted, then /usr/share/apkstudio or a subdirectory seems like the best place to put them. The guidelines I'm following can be found [here](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Directories), which suggest that /opt is primarily for large packages like JVMs. [The Filesystem Hierarchy Standard section on /opt](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s13.html) also implies that it's primarily for entire packages rather than components of one.

**Comment by vaibhavpandeyvpz** [comment]
Ok, done implementing that (see [here](https://github.com/vaibhavpandeyvpz/apkstudio/commit/214f6d7abb86873e8376de3b655f6123bc7a1db0#diff-a91ba21beccc055c394de4eb26424c7eR78))! But cannot test the build, as I don't have a linux machine atm.

**Comment by wlritchi** [comment]
Works for me; I've just pushed a version of the package that uses this. Thanks!
