### ISSUE TITLE
Dark theme setting doesn't seems working 

### ISSUE THREAD

**Issue by MakarenkoPavel** [vaibhavpandeyvpz/apkstudio#124]
When I select dark theme in appearance settings nothing happens

**Comment by vaibhavpandeyvpz** [comment]
It actually requires you to restart [APK Studio](https://github.com/vaibhavpandeyvpz/apkstudio) in order to have it in effect. I have updated it to notify and auto-restart itself (only if the user wishes to) since release [5.0.3](https://github.com/vaibhavpandeyvpz/apkstudio/releases/tag/5.0.3). See [004720b](https://github.com/vaibhavpandeyvpz/apkstudio/commit/004720bdf88c698ecbf170b91fa8125e9994249a) commit.
