### ISSUE TITLE
It seems there is no auto configuration for java related paths 

### ISSUE THREAD

**Issue by MakarenkoPavel** [vaibhavpandeyvpz/apkstudio#125]
I have java path in system variables but it necessary  to configure all paths manually

**Comment by vaibhavpandeyvpz** [comment]
I have now updated it to look for **adb** & **java** executables (the better way) now. It is built-in since release [5.0.3](https://github.com/vaibhavpandeyvpz/apkstudio/releases/tag/5.0.3). See [004720b](https://github.com/vaibhavpandeyvpz/apkstudio/commit/004720bdf88c698ecbf170b91fa8125e9994249a) commit.
