### ISSUE TITLE
Recompilation failed

### ISSUE THREAD

**Issue by gloeyisk** [vaibhavpandeyvpz/apkstudio#134]
This is happened from both APKTool and APK Studio. Here's the [log](https://del.dog/RecompilationFailed).
Edit: I know this issue already discussed but in this case I need `Decode Resources`. Any helps will be appreciated and I won't asking repeated same questions.

**Comment by gloeyisk** [comment]
It's doesn't meant APKTool related, I just said I tested both tools and did the same errors.
Not a problem if you close this issue, but, any idea to solve them?

**Comment by vaibhavpandeyvpz** [comment]
The problem with resources is with the `framework-res.apk` not being up-to-date or not compatible with the app you are decompiling. Since you seem to be decompiling a system app, you have to get the `framework-res.apk` from the phone or ROM you extracted the app from and install it with `apktool if <your-apk>`.

**Comment by gloeyisk** [comment]
> The problem with resources is with the `framework-res.apk` not being up-to-date or not compatible with the app you are decompiling. Since you seem to be decompiling a system app, you have to get the `framework-res.apk` from the phone or ROM you extracted the app from and install it with `apktool if <your-framework-apk>`.

I already install the whole framework with those commands, yes. But nothing happened, the errors still appeared.

**Comment by vaibhavpandeyvpz** [comment]
Then [this](https://github.com/iBotPeaches/Apktool/issues/new) is the right place to seek help for sure.
