### ISSUE TITLE
Crash when trying to open styles.xml

### ISSUE THREAD

**Issue by ensingerphilipp** [vaibhavpandeyvpz/apkstudio#154]
There is a seemingly random weird problem in that the Application crashes as soon as you try to open (double click) the styles.xml file often in the /res/values/ folder of apk´s.

Im on Windows if that makes a difference

**Comment by vaibhavpandeyvpz** [comment]
Can you please share the contents of the file here for me to inspect?

**Comment by eXspir3** [comment]
I now encountered this bug with another apk again the styles.xml --> Here are the 2 styles.xml Files:
[styles.zip](https://github.com/vaibhavpandeyvpz/apkstudio/files/4098031/styles.zip)

**Comment by Ibuprophen** [comment]
Have you tried to open the file using Notepad++? 

https://notepad-plus-plus.org

It's a really powerful (and free) software that I use as one of my primary editors for various/most files from a decompiled app. 

I'm just assuming that it may/might be crashing because it doesn't have a reliable software/editor to open them all with. 

Just taking a guess... 


~Ibuprophen

**Comment by eXspir3** [comment]
No thats not the case. I do have notepad++ installed, and it opens even in normal windows notepad.

The Problem i am discribing is only occuring if trying to open the files inside the APKStudio environment.

**Comment by vaibhavpandeyvpz** [comment]
Should be something with syntax highlighting. I’ll check tomorrow.

**Comment by vaibhavpandeyvpz** [comment]
Those files work fine for me. Cannot reproduce it.
