### ISSUE TITLE
APK debugging support (breakpoints, step over, variables, etc)

### ISSUE THREAD

**Issue by eladnava** [vaibhavpandeyvpz/apkstudio#23]
First off, APK Studio is awesome! Finally, an IDE for reversing Android apps.

I think that adding "debug" functionality to APKs (either via Java or Smali code) would be sick -- it's possible today via an external IDE (such as Eclipse/IntelliJ/Android Studio), but if it was built-in to APK Studio, it would really complete the tool.

Is this something you guys would consider?

**Comment by Cpruce** [comment]
I too am very interested in this feature!

**Comment by Surendrajat** [comment]
As of 2016 `smali debugging` feature had been dropped from **Apktool** - the core tool to power APK Studio. And without it I really don't have any idea how to implement now. Even if I try to implement it somehow, it will only increase the complexity of otherwise so simple IDE.
I'd recommend you to use [smalidea](https://github.com/JesusFreke/smali/wiki/smalidea) plugin of Android Studio which is far better at this job.
